[package]
name = "cui"
version = "0.1.0"
authors = ["Natanael Rabello <natanaeljrabello@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
euclid = "0.22.6"

[[example]]
name = "demo"
[[example]]
name = "mgmt"
